version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - echo "Enviando comando para EC2 via SSM"
      - aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids "i-0b5cb111f39d1f22a" \
          --comment "Deploy Odoo via docker-compose" \
          --parameters 'commands=[
            "cd /home/ubuntu/infra-odoo-aws",
            "git pull",
            "docker compose down",
            "docker compose up -d"
          ]' \
          --region us-east-1
