version: "3.8"

services:
  odoo:
    image: odoo:16
    container_name: odoo16
    ports:
      - "8069:8069"
    environment:
      - HOST=${DB_HOST}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    volumes:
      - odoo-data:/var/lib/odoo
    restart: unless-stopped

volumes:
  odoo-data:
