version: "3.8"

services:
  odoo:
    image: odoo:16
    container_name: odoo16
    ports:
      - "8069:8069"
    command: ["odoo", "-c", "/etc/odoo/odoo.conf", "--dev=reload", "--xmlrpc-interface=0.0.0.0"]
    env_file:
      - .env
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

volumes:
  odoo-data:
