name: Deploy Odoo via CodeBuild + SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: codebuild-odoo-deploy-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy via SSM para EC2 privada
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "i-0b5cb111f39d1f22a" \
            --comment "Deploy do Odoo" \
            --parameters 'commands=[
              "cd /home/ubuntu/infra-odoo",
              "git pull",
              "docker compose down",
              "docker compose up -d"
            ]' \
            --region us-east-1
